### ISSUE TITLE
bwa-mem2 "{tmp}.0000.bam": File exists

### ISSUE THREAD

**Issue by RvV1979** [moiexpositoalonsolab/grenepipe#28]
Hi, 
I am running grenepipe (v0.10.0) via slurm and my map_reads jobs using bwa-mem2 result in the following error (from samtools):
```
[E::hts_open_format] Failed to open file "{tmp}.0000.bam" : File exists
samtools sort: failed to create temporary file "{tmp}.0000.bam": File exists
```
I suspect this is because different jobs write temporary bam files with the same names to the output base directory. Any suggestion for a fix ? 
Thanks

**Comment by lczech** [comment]
Hi @RvV1979,

sorry you ran into this - that particular bug had been solved in the meantime after release v0.10.0, but I did not create a new release since. I have now, see [grenepipe v0.11.0](https://github.com/moiexpositoalonsolab/grenepipe/releases/tag/v0.11.0), which fixes this. You will have to edit the first `data` section of your `config.yaml` a little bit to work with the new release, and maybe some more sections - see its config file for the expected format.

Cheers
Lucas

**Comment by RvV1979** [comment]
Hi Lucas, 
Thanks for the quick reply and for creating a new release based on the latest changes. However, I changed to grenepipe v0.11.0 and the issue remains*. Any advice or assistance would be greatly appreciated. 

*FYI, I did not encounter this issue previously when using bwa-mem instead of bwa-mem2 for read mapping.

**Comment by lczech** [comment]
Oh I see, that was indeed a subtle bug in the way that the particular script you pointed out uses the `{tmp}` variable... Fixed now on the master branch. Could you please try with that (the green Code button [here](https://github.com/moiexpositoalonsolab/grenepipe), and then Download ZIP), and see if that works?

Thanks,
Lucas

**Comment by RvV1979** [comment]
Tried and the issue is resolved. Thanks!

**Comment by lczech** [comment]
Awesome!
