### ISSUE TITLE
ERROR conda.core.link:_execute(938): An error occurred while installing package (Grenepipe v0.15.0)

### ISSUE THREAD

**Issue by athenasyarifa** [moiexpositoalonsolab/grenepipe#65]
Hi Lucas, 

Thanks for making and maintaining this awesome tool! Second time grenepipe user here! So I used to run grenepipe v0.12.2 for my first project successfully, and now I am trying to install and run grenepipe v.0.15.0 according to the wiki instructions. Initial dry run seemed spotless (attached log file below), so I decided to go ahead and run the whole batch for 103 samples. 

[dry-run.log](https://github.com/user-attachments/files/20441238/2025-05-26T130335.393253.log)

However, I encountered an error related to conda and maybe due to the lack of internet connection on the compute node on the uni cluster (?) or lack of root permission (?). I put the main error message below, and it looked like it was related to the installation of GenomeInfoDbData, which is a recent feature update in grenepipe v0.14.0. I googled the problem, but nothing seemed particularly helpful. I was wondering if you could help me pinpoint what's the problem here. Any help would be greatly appreciated!

```
ERROR conda.core.link:_execute(938): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.13-r44hdfd78af_0'.
Rolling back transaction: ...working... done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.13-r44hdfd78af_0
location of failed script: /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: ++ dirname -- /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/installBiocDataPackage.sh
+ SCRIPT_DIR=/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/../share/bioconductor-data-packages
+ json=/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/../share/bioconductor-data-packages/dataURLs.json
++ yq '."genomeinfodbdata-1.2.13".fn' /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/../share/bioconductor-data-packages/dataURLs.json
+ FN='"GenomeInfoDbData_1.2.13.tar.gz"'
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.13".urls[]' /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/../share/bioconductor-data-packages/dataURLs.json
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
+ URLS+=($value)
+ IFS=
+ read -r value
++ yq '."genomeinfodbdata-1.2.13".md5' /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/bin/../share/bioconductor-data-packages/dataURLs.json
+ MD5='"8798e58b89d84d9fa6a85f2191704668"'
+ STAGING=/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/share/genomeinfodbdata-1.2.13
+ mkdir -p /dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/share/genomeinfodbdata-1.2.13
+ TARBALL='/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2023__Pmon_pop_gen/3__hybrid_zone/0__variant_calling/scripts/grenepipe/workflow/envs/3d0e2f92ae2581556115b73a2783f5a7_/share/genomeinfodbdata-1.2.13/"GenomeInfoDbData_1.2.13.tar.gz"'
+ SUCCESS=0
+ for URL in ${URLS[@]}
++ echo '"https://bioconductor.org/packages/3.20/data/annotation/src/contrib/GenomeInfoDbData_1.2.13.tar.gz"'
++ tr -d '"'
+ URL=https://bioconductor.org/packages/3.20/data/annotation/src/contrib/GenomeInfoDbData_1.2.13.tar.gz
++ echo '"8798e58b89d84d9fa6a85f2191704668"'
++ tr -d '"'
+ MD5=8798e58b89d84d9fa6a85f2191704668
+ curl -L https://bioconductor.org/packages/3.20/data/annotation/src/contrib/GenomeInfoDbData_1.2.13.tar.gz
```

I attached here the log file of the run with the error: 
[2025-05-26T131759.486606.log](https://github.com/user-attachments/files/20441333/2025-05-26T131759.486606.log)

Thank you in advance for your help!
Cheers, 
Rifa

**Comment by lczech** [comment]
Hi Rifa @athenasyarifa,

thanks for using grenepipe! That looks like an issue with conda/mamba, and might be unrelated to grenepipe itself. It seems that the qualimap conda environment is the issue.

Can you try installing that environment on its own?

```
mamba create -f path/to/grenepipe/workflow/envs/qualimap.yaml
```
(replacing the path as needed)

And see if that works? Other than that, it might also work to just try again later. conda sometimes has these glitches... If it persists, let's see what we can do :-)

Cheers and so long
Lucas

**Comment by athenasyarifa** [comment]
Hi Lucas, 

Sorry for the delay, and thanks for the prompt reply. I tried installing the environment on its own and still faced with the same issue. I took a deep dive into the issue, and you were right, I can confirm that this is an issue with conda/mamba, specifically bioconda recipe for some bioconductor packages. I looked at several issues raised here: 

https://github.com/bioconda/bioconda-recipes/issues/13846
https://github.com/bioconda/bioconda-recipes/issues/31349
https://github.com/bioconda/bioconda-recipes/issues/28801
https://github.com/bioconda/bioconda-recipes/issues/36499

All of them are related to the post link on the conda installation, and it looks like it is a recurrent issue with bioconda recipe for bioconductor packages because they even made a dedicated page for it [here](https://bioconda.github.io/faqs.html#why-are-bioconductor-data-packages-failing-to-install). I tried downloading the package and installing it in the grenepipe conda environment, but I guess this won't work since the qualimap environment would be installed by snakemake. I also tried changing the version of the bioconductor-genomeinfodbdata, but it still did not work. So currently, I am still trying to find ways to work around the issue, and I guess this is a problem that is out of our hands (ppl in bioconda should be able to fix the post link issue). I would open an issue on their github, and let's see what they can come up with. 

Thanks anyway for responding!

Cheers, 
Rifa

**Comment by lczech** [comment]
Hi Rifa,

thanks for the update! Ah yes, the horrors of conda compatibility... I have wasted so many hours on such issues already, and it is so frustrating that with the whole conda universe, the "never change a running system" rule is futile, as they just keep breaking their own backwards compatibility... 

In your particular case, yes, reporting this to conda or bioconductor might make sense. Also, in order to get grenepipe to work for you in the meantime, you can try to work with a different version of qualimap. See the file `grenepipe/workflow/envs/qualimap.yaml` - there are some comments in there on other compatibility issues that I had in the past. Maybe try one of the older versions and see if that works?

Also, I just tried to reproduce this myself, using
```
cd path/to/grenepipe/workflow/envs/
micromamba activate grenepipe
mamba env create -f qualimap.yaml -n qualimap-v2.3.0
```
and that worked well for me. So unfortunately, I have no easy way of reproducing and testing your issue myself. If your error persists, I could try to get the exact versions of conda and mamba that you are using and see if I can reproduce with these - but it might be easier to try one of the other approaches first.

Cheers and so long
Lucas

**Comment by lczech** [comment]
You can also try to use a different version of mamba/conda yourself in the grenepipe environment.

For instance, in `grenepipe/workflow/envs/grenepipe.yaml`, you could try fixing the versions, and re-install that environment.
For me, these seem to work:
```
mamba 1.5.12
conda 24.11.3
```
Maybe that helps.

Cheers
Lucas

**Comment by athenasyarifa** [comment]
Hi Lucas, 

Thanks for the suggestions! 

> Also, in order to get grenepipe to work for you in the meantime, you can try to work with a different version of qualimap. See the file grenepipe/workflow/envs/qualimap.yaml - there are some comments in there on other compatibility issues that I had in the past. Maybe try one of the older versions and see if that works?

This was one of the first things I tried, unfortunately, the same error still occurred for me using `qualimap==2.2.2a` and `qualimap==2.2.2b`. 

>You can also try to use a different version of mamba/conda yourself in the grenepipe environment.

I also use `conda 24.11.3` and `mamba 1.5.12` in my grenepipe environment, and tried uninstalling and re-installing grenepipe.

Just out of curiosity, what version of `libcurl` and `linux` do you use? Some previous issues pages mentioned different versions of these that work for them. 

Cheers, 
Rifa

**Comment by lczech** [comment]
Huh okay, you tried all the usual tricks already! Very good, but now it gets harder for me to come up with creative ideas how to help you...

I'm on Ubuntu 20.04.6 LTS right now (really need to upgrade that...), with Linux kernel 5.15.0-139-generic.
My system curl version is 7.68.0, but within the grenepipe conda env, it is using 8.13.0 instead.

If the curl version might help: the `grenepipe/workflow/envs/grenepipe.yaml` env lists curl as a dependency as well, but currently without any version. You could try to request a particular version there to see if that solves the issue. If so, let me know, so that I can add that version to the env as well.

Cheers and so long
Lucas

**Comment by athenasyarifa** [comment]
Hi Lucas @lczech and everyone, 

I fixed the problem! I ended up uninstalling my conda and mamba, and reinstall them using miniforge3 the newest release. In the `qualimap.yaml` I also moved `bioconda` as the first line in the channel list and did not specify the version of `qualimap`, not sure if this makes a difference but I have a feeling it helped. Thanks for the help!

Cheers, 
Rifa

**Comment by lczech** [comment]
Hey Rifa @athenasyarifa, 

happy to hear that! And sorry that you had to go through this. Been there too times as well - rather annoying that the conda universe is suffering from these issues still...

Are there any changes to the grenepipe conda setup that you think would help others? I would like to keep the qualimap version specified for reproducibility, but if you think that e.g. changing channel order would help others, let me know!

Cheers
Lucas

**Comment by athenasyarifa** [comment]
I think this was a specific case for me, because previously I installed mamba and conda with an older release of Miniconda. Somehow changing to Miniforge3 newest release is what really helped for me, not necessarily the channel order. So I think there is no need for changes in the current conda setup. 

Cheers, 
Rifa

**Comment by lczech** [comment]
Okay, thank you! Yes, makes sense - I had trouble with older conda/mamba versions as well with more recent versions of Snakemake... So frustrating to be honest - a system whose purpose it is to ensure reproducibility, but is not backwards-compatible with itself. Well, it is a very hard problem, and would require a lot of work to get right, so I get it. But still annoying from time to time. Anyway, happy to hear that you solved it!
